name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit:
    strategy:
      matrix:
        python-version: [ "3.10" , "3.11", "3.12"]
        django-version: [ "3.2", "4.0", "4.1", "4.2", "5.0" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install Django==${{ matrix.django-version }}
      - run: pip install -r requirements.txt
      - run: python runtests.py
